name: Android Release CI

on:
  push:
    tags:
      - "*"
      - "!nightly*"

jobs:
  build:
    name: Build, Sign & Release
    runs-on: ubuntu-latest
    permissions: write-all
    steps:
      - name: Checkout project
        uses: actions/checkout@v4.2.2

      - name: set up JDK 17
        uses: actions/setup-java@v4.7.1
        with:
          java-version: "17"
          distribution: "temurin"
          cache: gradle

      - uses: actions/cache@v4.2.3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew clean && ./gradlew assembleRelease

      - name: Sign APK
        uses: ilharp/sign-android-release@v2.0.0
        # ID used to access action output
        id: sign_app
        with:
          signingKey: ${{ secrets.SIGNING_KEY }}
          keyAlias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEYSTORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}

      - name: Release to GitHub
        uses: svenstaro/upload-release-action@2.11.1
        with:
          file: ${{steps.sign_app.outputs.signedFile}}
          asset_name: PlayHex-${{ github.ref_name }}-signed.apk
          overwrite: true
